[2016Oct03 11:49:27,199][INFO ][][configurarLogger BSSIntLogger.java:67][APLICACION: PreMasivas - VERSION: 1.0]
[2016Oct03 11:49:27,225][INFO ][][configurarLogger BSSIntLogger.java:69][DESCRIPCION: Servicios de Integracion - PreActivaciones Masivas Lineas Prepago]
[2016Oct03 11:49:32,364][INFO ][][main FileMonitor.java:202][DirectoryListener en ejecucion...]
[2016Oct03 18:06:23,228][INFO ][][configurarLogger BSSIntLogger.java:67][APLICACION: PreMasivas - VERSION: 1.0]
[2016Oct03 18:06:23,258][INFO ][][configurarLogger BSSIntLogger.java:69][DESCRIPCION: Servicios de Integracion - PreActivaciones Masivas Lineas Prepago]
[2016Oct03 18:06:27,732][INFO ][][main FileMonitor.java:202][DirectoryListener en ejecucion...]
[2016Oct03 18:07:31,809][INFO ][][fileChanged DirectoryListener.java:196][No Existen Archivos por procesar...]
[2016Oct03 18:07:48,297][INFO ][][configurarLogger BSSIntLogger.java:67][APLICACION: PreMasivas - VERSION: 1.0]
[2016Oct03 18:07:48,368][INFO ][][configurarLogger BSSIntLogger.java:69][DESCRIPCION: Servicios de Integracion - PreActivaciones Masivas Lineas Prepago]
[2016Oct03 18:07:52,200][INFO ][][main FileMonitor.java:202][DirectoryListener en ejecucion...]
[2016Oct03 18:13:53,439][INFO ][][fileChanged DirectoryListener.java:133][******* En procesamiento 0]
[2016Oct03 18:13:53,441][INFO ][][fileChanged DirectoryListener.java:134][******* Cantidad Maxima Archivos 1]
[2016Oct03 18:13:53,444][INFO ][][fileChanged DirectoryListener.java:135][******* Archivos Encontrados 1]
[2016Oct03 18:13:53,446][INFO ][][fileChanged DirectoryListener.java:147][Archivo a procesar: DIG05028_1_OCCIDENTE_1.OUT]
[2016Oct03 18:13:53,464][INFO ][][getRequestFile DirectoryListener.java:265][Se validó el encabezado del archivo. Se preactivará el lote con Plan: Pre Activo BAM, Profile: 08]
[2016Oct03 18:13:53,546][INFO ][][getRequestFile DirectoryListener.java:304][Archivo DIG05028_1_OCCIDENTE_1.OUT Validado con exito]
[2016Oct03 18:13:53,548][INFO ][][getRequestFile DirectoryListener.java:308][Tiempo de ejecucion: 0s]
[2016Oct03 18:13:53,550][WARN ][][fileChanged DirectoryListener.java:176][DIG05028_1_OCCIDENTE_1.OUT]
[2016Oct03 18:13:53,939][INFO ][][fileChanged DirectoryListener.java:196][No Existen Archivos por procesar...]
[2016Oct03 18:13:57,650][INFO ][][configurarLogger BSSIntLogger.java:67][APLICACION: PreMasivas - VERSION: 1.0]
[2016Oct03 18:13:57,672][INFO ][][configurarLogger BSSIntLogger.java:69][DESCRIPCION: Servicios de Integracion - PreActivaciones Masivas Lineas Prepago]
[2016Oct03 18:13:57,729][INFO ][04125342996_1475534633467][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:13:58,989][INFO ][][fileChanged DirectoryListener.java:133][******* En procesamiento 1]
[2016Oct03 18:13:58,992][INFO ][][fileChanged DirectoryListener.java:134][******* Cantidad Maxima Archivos 1]
[2016Oct03 18:13:58,994][INFO ][][fileChanged DirectoryListener.java:135][******* Archivos Encontrados 1]
[2016Oct03 18:13:58,996][INFO ][][fileChanged DirectoryListener.java:190][¡¡¡No se procesaran los archivos presentes en el directorio de entrada!!!]
[2016Oct03 18:13:58,998][INFO ][][fileChanged DirectoryListener.java:191][Cantidad maxima de archivos a procesar: 1]
[2016Oct03 18:13:59,001][INFO ][][fileChanged DirectoryListener.java:192][Cantidad de archivos en procesamiento: 1]
[2016Oct03 18:13:59,099][INFO ][][fileChanged DirectoryListener.java:133][******* En procesamiento 1]
[2016Oct03 18:13:59,102][INFO ][][fileChanged DirectoryListener.java:134][******* Cantidad Maxima Archivos 1]
[2016Oct03 18:13:59,104][INFO ][][fileChanged DirectoryListener.java:135][******* Archivos Encontrados 1]
[2016Oct03 18:13:59,107][INFO ][][fileChanged DirectoryListener.java:190][¡¡¡No se procesaran los archivos presentes en el directorio de entrada!!!]
[2016Oct03 18:13:59,110][INFO ][][fileChanged DirectoryListener.java:191][Cantidad maxima de archivos a procesar: 1]
[2016Oct03 18:13:59,113][INFO ][][fileChanged DirectoryListener.java:192][Cantidad de archivos en procesamiento: 1]
[2016Oct03 18:14:14,232][INFO ][04125342996_1475534633467][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.mdb.ProcessInboxMDBean.onMessage(ProcessInboxMDBean.java:127)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:14:14,346][INFO ][04125342996_1475534633467][onMessage ProcessInboxRetryMDBean.java:123][Mensaje recibido con exito en la cola de REINTENTOS ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475534633467, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475534633467, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:13:53, _rc_resultado=0, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=1.0, _rc_razon=Asignacion exitosa, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:14:14,347][INFO ][04125342996_1475534633467][execute RetryQueueSubmiterDelegator.java:171][Reintentos: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola de reintentos | info: ActivationOrder enviado a la cola de reintentos | vto: {}}]
[2016Oct03 18:14:14,348][INFO ][04125342996_1475534633467][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:14:14,366][INFO ][04125342996_1475534633467][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:14:14,368][INFO ][04125342996_1475534633467][onMessage ProcessInboxMDBean.java:129][Solicitud procesada ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475534633467, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, cantLineas=1, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475534633467, _rc_razon_create=Error en la creacion del suscriptor en RTBS, pin=0000, _rc_reintentos=0.0, _rc_razon=Request enviado a la cola para el registro de estados, puk2=60525523, _rc_resultado_create=100, order=, status=0, profile=08, reintentosIL=0, puk=15045492, iccid=8958021306050000220F, pin1=1108, fecha=2016-10-03 18:13:53, relatesTo=, msisdn=04125342996, _rc_resultado=0, sMessage=, task=}}]
[2016Oct03 18:14:29,355][INFO ][04125342996_1475534633467][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.retry.mdb.ProcessInboxRetryMDBean.onMessage(ProcessInboxRetryMDBean.java:125)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:14:29,367][INFO ][04125342996_1475534633467][onMessage ProcessInboxRetryMDBean.java:123][Mensaje recibido con exito en la cola de REINTENTOS ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475534633467, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475534633467, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:13:53, _rc_resultado=0, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=2.0, _rc_razon=Asignacion exitosa, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:14:29,368][INFO ][04125342996_1475534633467][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:14:29,381][INFO ][04125342996_1475534633467][execute RetryQueueSubmiterDelegator.java:171][Reintentos: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola de reintentos | info: ActivationOrder enviado a la cola de reintentos | vto: {}}]
[2016Oct03 18:14:29,393][INFO ][04125342996_1475534633467][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:14:29,394][INFO ][04125342996_1475534633467][onMessage ProcessInboxRetryMDBean.java:127][Solicitud procesada ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:14:44,373][INFO ][04125342996_1475534633467][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.retry.mdb.ProcessInboxRetryMDBean.onMessage(ProcessInboxRetryMDBean.java:125)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:14:44,387][INFO ][04125342996_1475534633467][onMessage ProcessInboxRetryMDBean.java:123][Mensaje recibido con exito en la cola de REINTENTOS ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475534633467, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475534633467, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:13:53, _rc_resultado=0, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=3.0, _rc_razon=Asignacion exitosa, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:14:44,388][INFO ][04125342996_1475534633467][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:14:44,389][INFO ][04125342996_1475534633467][execute RetryQueueSubmiterDelegator.java:171][Reintentos: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola de reintentos | info: ActivationOrder enviado a la cola de reintentos | vto: {}}]
[2016Oct03 18:14:44,401][INFO ][04125342996_1475534633467][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:14:44,402][INFO ][04125342996_1475534633467][onMessage ProcessInboxRetryMDBean.java:127][Solicitud procesada ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:14:59,395][INFO ][04125342996_1475534633467][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.retry.mdb.ProcessInboxRetryMDBean.onMessage(ProcessInboxRetryMDBean.java:125)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:14:59,413][INFO ][04125342996_1475534633467][processRequest RC.java:60][Inicio de Servicio en Fase 1: generar.archivo.salida]
[2016Oct03 18:14:59,423][INFO ][04125342996_1475534633467][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:14:59,424][INFO ][04125342996_1475534633467][onMessage ProcessInboxRetryMDBean.java:127][Solicitud procesada ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:14:59,442][INFO ][04125342996_1475534633467][execute FileWriterDelegator.java:178][********************* procesados: 1]
[2016Oct03 18:14:59,453][ERROR][04125342996_1475534633467][crearArchivo FileWriterDelegator.java:301][Se instalo el lote DIG05028_1_OCCIDENTE_1.OUT con un total de lineas [1]. 
Cantidad de Errores encontrados: 1.
]
[2016Oct03 18:14:59,461][ERROR][04125342996_1475534633467][execute FileWriterDelegator.java:247][Error ocurrido durante la generacion del archivo de salida]
java.sql.SQLException: No more data to read from socket
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:125)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:162)
	at oracle.jdbc.driver.DatabaseError.check_error(DatabaseError.java:885)
	at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:994)
	at oracle.jdbc.driver.T4CMAREngine.unmarshalSB1(T4CMAREngine.java:951)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:435)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:182)
	at oracle.jdbc.driver.T4CPreparedStatement.execute_for_rows(T4CPreparedStatement.java:630)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1081)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:2905)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:2977)
	at weblogic.jdbc.wrapper.PreparedStatement.executeUpdate(PreparedStatement.java:147)
	at ve.com.digitel.premasivas.delegator.FileWriterDelegator.execute(FileWriterDelegator.java:198)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.mdb.ProcessInboxMDBean.onMessage(ProcessInboxMDBean.java:127)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
[2016Oct03 18:14:59,466][INFO ][04125342996_1475534633467][processRequest RC.java:70][Fin Servicio en Fase 1: generar.archivo.salida Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 1 | reasonCode: Error generando archivo de salida | info:  | vto: {}}]
[2016Oct03 18:14:59,467][INFO ][04125342996_1475534633467][onMessage ProcessInboxMDBean.java:129][Solicitud procesada ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475534633467, OldTarget=crear.suscriptor.rtbs, Target=generar.archivo.salida} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475534633467, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:13:53, _rc_resultado=1, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=3.0, _rc_razon=Error generando archivo de salida, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, error=09, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:15:19,820][INFO ][][configurarLogger BSSIntLogger.java:67][APLICACION: PreMasivas - VERSION: 1.0]
[2016Oct03 18:15:19,862][INFO ][][configurarLogger BSSIntLogger.java:69][DESCRIPCION: Servicios de Integracion - PreActivaciones Masivas Lineas Prepago]
[2016Oct03 18:15:23,735][INFO ][][main FileMonitor.java:202][DirectoryListener en ejecucion...]
[2016Oct03 18:15:50,718][INFO ][][configurarLogger BSSIntLogger.java:67][APLICACION: PreMasivas - VERSION: 1.0]
[2016Oct03 18:15:50,737][INFO ][][configurarLogger BSSIntLogger.java:69][DESCRIPCION: Servicios de Integracion - PreActivaciones Masivas Lineas Prepago]
[2016Oct03 18:15:54,436][INFO ][][main FileMonitor.java:202][DirectoryListener en ejecucion...]
[2016Oct03 18:22:12,727][INFO ][][configurarLogger BSSIntLogger.java:67][APLICACION: PreMasivas - VERSION: 1.0]
[2016Oct03 18:22:12,747][INFO ][][configurarLogger BSSIntLogger.java:69][DESCRIPCION: Servicios de Integracion - PreActivaciones Masivas Lineas Prepago]
[2016Oct03 18:22:16,132][INFO ][][main FileMonitor.java:202][DirectoryListener en ejecucion...]
[2016Oct03 18:22:54,032][INFO ][][fileChanged DirectoryListener.java:196][No Existen Archivos por procesar...]
[2016Oct03 18:23:30,358][INFO ][][configurarLogger BSSIntLogger.java:67][APLICACION: PreMasivas - VERSION: 1.0]
[2016Oct03 18:23:30,377][INFO ][][configurarLogger BSSIntLogger.java:69][DESCRIPCION: Servicios de Integracion - PreActivaciones Masivas Lineas Prepago]
[2016Oct03 18:23:33,544][INFO ][][main FileMonitor.java:202][DirectoryListener en ejecucion...]
[2016Oct03 18:26:08,487][INFO ][][fileChanged DirectoryListener.java:133][******* En procesamiento 0]
[2016Oct03 18:26:08,490][INFO ][][fileChanged DirectoryListener.java:134][******* Cantidad Maxima Archivos 1]
[2016Oct03 18:26:08,492][INFO ][][fileChanged DirectoryListener.java:135][******* Archivos Encontrados 1]
[2016Oct03 18:26:08,494][INFO ][][fileChanged DirectoryListener.java:147][Archivo a procesar: DIG05028_1_OCCIDENTE_1.OUT]
[2016Oct03 18:26:08,512][INFO ][][getRequestFile DirectoryListener.java:265][Se validó el encabezado del archivo. Se preactivará el lote con Plan: Pre Activo BAM, Profile: 08]
[2016Oct03 18:26:08,566][INFO ][][getRequestFile DirectoryListener.java:304][Archivo DIG05028_1_OCCIDENTE_1.OUT Validado con exito]
[2016Oct03 18:26:08,569][INFO ][][getRequestFile DirectoryListener.java:308][Tiempo de ejecucion: 0s]
[2016Oct03 18:26:08,570][WARN ][][fileChanged DirectoryListener.java:176][DIG05028_1_OCCIDENTE_1.OUT]
[2016Oct03 18:26:11,549][INFO ][][fileChanged DirectoryListener.java:196][No Existen Archivos por procesar...]
[2016Oct03 18:26:11,845][INFO ][][configurarLogger BSSIntLogger.java:67][APLICACION: PreMasivas - VERSION: 1.0]
[2016Oct03 18:26:11,865][INFO ][][configurarLogger BSSIntLogger.java:69][DESCRIPCION: Servicios de Integracion - PreActivaciones Masivas Lineas Prepago]
[2016Oct03 18:26:11,884][INFO ][04125342996_1475535368515][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:26:28,171][INFO ][04125342996_1475535368515][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.mdb.ProcessInboxMDBean.onMessage(ProcessInboxMDBean.java:127)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:26:28,259][INFO ][04125342996_1475535368515][onMessage ProcessInboxRetryMDBean.java:123][Mensaje recibido con exito en la cola de REINTENTOS ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475535368515, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475535368515, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:26:08, _rc_resultado=0, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=1.0, _rc_razon=Asignacion exitosa, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:26:28,260][INFO ][04125342996_1475535368515][execute RetryQueueSubmiterDelegator.java:171][Reintentos: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola de reintentos | info: ActivationOrder enviado a la cola de reintentos | vto: {}}]
[2016Oct03 18:26:28,261][INFO ][04125342996_1475535368515][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:26:28,277][INFO ][04125342996_1475535368515][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:26:28,279][INFO ][04125342996_1475535368515][onMessage ProcessInboxMDBean.java:129][Solicitud procesada ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475535368515, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, cantLineas=1, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475535368515, _rc_razon_create=Error en la creacion del suscriptor en RTBS, pin=0000, _rc_reintentos=0.0, _rc_razon=Request enviado a la cola para el registro de estados, puk2=60525523, _rc_resultado_create=100, order=, status=0, profile=08, reintentosIL=0, puk=15045492, iccid=8958021306050000220F, pin1=1108, fecha=2016-10-03 18:26:08, relatesTo=, msisdn=04125342996, _rc_resultado=0, sMessage=, task=}}]
[2016Oct03 18:26:43,269][INFO ][04125342996_1475535368515][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.retry.mdb.ProcessInboxRetryMDBean.onMessage(ProcessInboxRetryMDBean.java:125)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:26:43,282][INFO ][04125342996_1475535368515][onMessage ProcessInboxRetryMDBean.java:123][Mensaje recibido con exito en la cola de REINTENTOS ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475535368515, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475535368515, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:26:08, _rc_resultado=0, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=2.0, _rc_razon=Asignacion exitosa, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:26:43,284][INFO ][04125342996_1475535368515][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:26:43,285][INFO ][04125342996_1475535368515][execute RetryQueueSubmiterDelegator.java:171][Reintentos: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola de reintentos | info: ActivationOrder enviado a la cola de reintentos | vto: {}}]
[2016Oct03 18:26:43,297][INFO ][04125342996_1475535368515][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:26:43,298][INFO ][04125342996_1475535368515][onMessage ProcessInboxRetryMDBean.java:127][Solicitud procesada ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:26:58,290][INFO ][04125342996_1475535368515][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.retry.mdb.ProcessInboxRetryMDBean.onMessage(ProcessInboxRetryMDBean.java:125)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:26:58,302][INFO ][04125342996_1475535368515][onMessage ProcessInboxRetryMDBean.java:123][Mensaje recibido con exito en la cola de REINTENTOS ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475535368515, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475535368515, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:26:08, _rc_resultado=0, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=3.0, _rc_razon=Asignacion exitosa, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:26:58,304][INFO ][04125342996_1475535368515][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:26:58,305][INFO ][04125342996_1475535368515][execute RetryQueueSubmiterDelegator.java:171][Reintentos: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola de reintentos | info: ActivationOrder enviado a la cola de reintentos | vto: {}}]
[2016Oct03 18:26:58,318][INFO ][04125342996_1475535368515][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:26:58,319][INFO ][04125342996_1475535368515][onMessage ProcessInboxRetryMDBean.java:127][Solicitud procesada ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:27:13,310][INFO ][04125342996_1475535368515][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.retry.mdb.ProcessInboxRetryMDBean.onMessage(ProcessInboxRetryMDBean.java:125)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:27:13,328][INFO ][04125342996_1475535368515][processRequest RC.java:60][Inicio de Servicio en Fase 1: generar.archivo.salida]
[2016Oct03 18:27:13,339][INFO ][04125342996_1475535368515][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:27:13,340][INFO ][04125342996_1475535368515][onMessage ProcessInboxRetryMDBean.java:127][Solicitud procesada ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:27:13,344][INFO ][04125342996_1475535368515][execute FileWriterDelegator.java:178][********************* procesados: 1]
[2016Oct03 18:27:13,347][ERROR][04125342996_1475535368515][crearArchivo FileWriterDelegator.java:301][Se instalo el lote DIG05028_1_OCCIDENTE_1.OUT con un total de lineas [1]. 
Cantidad de Errores encontrados: 1.
]
[2016Oct03 18:27:13,353][ERROR][04125342996_1475535368515][execute FileWriterDelegator.java:247][Error ocurrido durante la generacion del archivo de salida]
java.sql.SQLException: OALL8 is in an inconsistent state.
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:125)
	at oracle.jdbc.driver.T4C8Oall.init(T4C8Oall.java:309)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:167)
	at oracle.jdbc.driver.T4CPreparedStatement.execute_for_rows(T4CPreparedStatement.java:630)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1081)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:2905)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:2977)
	at weblogic.jdbc.wrapper.PreparedStatement.executeUpdate(PreparedStatement.java:147)
	at ve.com.digitel.premasivas.delegator.FileWriterDelegator.execute(FileWriterDelegator.java:198)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.mdb.ProcessInboxMDBean.onMessage(ProcessInboxMDBean.java:127)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
[2016Oct03 18:27:13,357][INFO ][04125342996_1475535368515][processRequest RC.java:70][Fin Servicio en Fase 1: generar.archivo.salida Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 1 | reasonCode: Error generando archivo de salida | info:  | vto: {}}]
[2016Oct03 18:27:13,358][INFO ][04125342996_1475535368515][onMessage ProcessInboxMDBean.java:129][Solicitud procesada ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475535368515, OldTarget=crear.suscriptor.rtbs, Target=generar.archivo.salida} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475535368515, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:26:08, _rc_resultado=1, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=3.0, _rc_razon=Error generando archivo de salida, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, error=09, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:34:07,908][INFO ][][fileChanged DirectoryListener.java:133][******* En procesamiento 0]
[2016Oct03 18:34:07,911][INFO ][][fileChanged DirectoryListener.java:134][******* Cantidad Maxima Archivos 1]
[2016Oct03 18:34:07,913][INFO ][][fileChanged DirectoryListener.java:135][******* Archivos Encontrados 1]
[2016Oct03 18:34:07,915][INFO ][][fileChanged DirectoryListener.java:147][Archivo a procesar: DIG05028_1_OCCIDENTE_1.OUT]
[2016Oct03 18:34:07,927][INFO ][][getRequestFile DirectoryListener.java:265][Se validó el encabezado del archivo. Se preactivará el lote con Plan: Pre Activo BAM, Profile: 08]
[2016Oct03 18:34:07,931][INFO ][][getRequestFile DirectoryListener.java:304][Archivo DIG05028_1_OCCIDENTE_1.OUT Validado con exito]
[2016Oct03 18:34:07,933][INFO ][][getRequestFile DirectoryListener.java:308][Tiempo de ejecucion: 0s]
[2016Oct03 18:34:07,936][WARN ][][fileChanged DirectoryListener.java:176][DIG05028_1_OCCIDENTE_1.OUT]
[2016Oct03 18:34:08,286][INFO ][][configurarLogger BSSIntLogger.java:67][APLICACION: PreMasivas - VERSION: 1.0]
[2016Oct03 18:34:08,306][INFO ][][configurarLogger BSSIntLogger.java:69][DESCRIPCION: Servicios de Integracion - PreActivaciones Masivas Lineas Prepago]
[2016Oct03 18:34:08,325][INFO ][04125342996_1475535847930][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:34:25,382][INFO ][04125342996_1475535847930][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.mdb.ProcessInboxMDBean.onMessage(ProcessInboxMDBean.java:127)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:34:25,479][INFO ][04125342996_1475535847930][onMessage ProcessInboxRetryMDBean.java:123][Mensaje recibido con exito en la cola de REINTENTOS ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475535847930, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475535847930, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:34:07, _rc_resultado=0, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=1.0, _rc_razon=Asignacion exitosa, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:34:25,480][INFO ][04125342996_1475535847930][execute RetryQueueSubmiterDelegator.java:171][Reintentos: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola de reintentos | info: ActivationOrder enviado a la cola de reintentos | vto: {}}]
[2016Oct03 18:34:25,481][INFO ][04125342996_1475535847930][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:34:25,497][INFO ][04125342996_1475535847930][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:34:25,499][INFO ][04125342996_1475535847930][onMessage ProcessInboxMDBean.java:129][Solicitud procesada ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475535847930, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, cantLineas=1, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475535847930, _rc_razon_create=Error en la creacion del suscriptor en RTBS, pin=0000, _rc_reintentos=0.0, _rc_razon=Request enviado a la cola para el registro de estados, puk2=60525523, _rc_resultado_create=100, order=, status=0, profile=08, reintentosIL=0, puk=15045492, iccid=8958021306050000220F, pin1=1108, fecha=2016-10-03 18:34:07, relatesTo=, msisdn=04125342996, _rc_resultado=0, sMessage=, task=}}]
[2016Oct03 18:34:40,487][INFO ][04125342996_1475535847930][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.retry.mdb.ProcessInboxRetryMDBean.onMessage(ProcessInboxRetryMDBean.java:125)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:34:40,500][INFO ][04125342996_1475535847930][onMessage ProcessInboxRetryMDBean.java:123][Mensaje recibido con exito en la cola de REINTENTOS ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475535847930, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475535847930, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:34:07, _rc_resultado=0, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=2.0, _rc_razon=Asignacion exitosa, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:34:40,501][INFO ][04125342996_1475535847930][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:34:40,502][INFO ][04125342996_1475535847930][execute RetryQueueSubmiterDelegator.java:171][Reintentos: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola de reintentos | info: ActivationOrder enviado a la cola de reintentos | vto: {}}]
[2016Oct03 18:34:40,515][INFO ][04125342996_1475535847930][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:34:40,516][INFO ][04125342996_1475535847930][onMessage ProcessInboxRetryMDBean.java:127][Solicitud procesada ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:34:55,507][INFO ][04125342996_1475535847930][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.retry.mdb.ProcessInboxRetryMDBean.onMessage(ProcessInboxRetryMDBean.java:125)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:34:55,519][INFO ][04125342996_1475535847930][onMessage ProcessInboxRetryMDBean.java:123][Mensaje recibido con exito en la cola de REINTENTOS ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475535847930, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475535847930, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:34:07, _rc_resultado=0, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=3.0, _rc_razon=Asignacion exitosa, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:34:55,521][INFO ][04125342996_1475535847930][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:34:55,522][INFO ][04125342996_1475535847930][execute RetryQueueSubmiterDelegator.java:171][Reintentos: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola de reintentos | info: ActivationOrder enviado a la cola de reintentos | vto: {}}]
[2016Oct03 18:34:55,533][INFO ][04125342996_1475535847930][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:34:55,534][INFO ][04125342996_1475535847930][onMessage ProcessInboxRetryMDBean.java:127][Solicitud procesada ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:35:10,527][INFO ][04125342996_1475535847930][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.retry.mdb.ProcessInboxRetryMDBean.onMessage(ProcessInboxRetryMDBean.java:125)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:35:10,545][INFO ][04125342996_1475535847930][processRequest RC.java:60][Inicio de Servicio en Fase 1: generar.archivo.salida]
[2016Oct03 18:35:10,555][INFO ][04125342996_1475535847930][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:35:10,556][INFO ][04125342996_1475535847930][onMessage ProcessInboxRetryMDBean.java:127][Solicitud procesada ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:35:10,561][INFO ][04125342996_1475535847930][execute FileWriterDelegator.java:178][********************* procesados: 1]
[2016Oct03 18:35:10,563][ERROR][04125342996_1475535847930][crearArchivo FileWriterDelegator.java:301][Se instalo el lote DIG05028_1_OCCIDENTE_1.OUT con un total de lineas [1]. 
Cantidad de Errores encontrados: 1.
]
[2016Oct03 18:35:10,600][ERROR][04125342996_1475535847930][execute FileWriterDelegator.java:247][Error ocurrido durante la generacion del archivo de salida]
javax.naming.NameNotFoundException: Unable to resolve 'jdbc.datasource.res' Resolved jdbc.datasource; remaining name 'res'
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:230)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.WLEventContextImpl.lookup(WLEventContextImpl.java:256)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.premasivas.delegator.FileWriterDelegator.execute(FileWriterDelegator.java:189)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.mdb.ProcessInboxMDBean.onMessage(ProcessInboxMDBean.java:127)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
[2016Oct03 18:35:10,604][INFO ][04125342996_1475535847930][processRequest RC.java:70][Fin Servicio en Fase 1: generar.archivo.salida Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 1 | reasonCode: Error generando archivo de salida | info:  | vto: {}}]
[2016Oct03 18:35:10,605][INFO ][04125342996_1475535847930][onMessage ProcessInboxMDBean.java:129][Solicitud procesada ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475535847930, OldTarget=crear.suscriptor.rtbs, Target=generar.archivo.salida} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475535847930, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:34:07, _rc_resultado=1, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=3.0, _rc_razon=Error generando archivo de salida, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, error=09, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:41:00,969][INFO ][][fileChanged DirectoryListener.java:133][******* En procesamiento 1]
[2016Oct03 18:41:00,971][INFO ][][fileChanged DirectoryListener.java:134][******* Cantidad Maxima Archivos 1]
[2016Oct03 18:41:00,973][INFO ][][fileChanged DirectoryListener.java:135][******* Archivos Encontrados 1]
[2016Oct03 18:41:00,975][INFO ][][fileChanged DirectoryListener.java:190][¡¡¡No se procesaran los archivos presentes en el directorio de entrada!!!]
[2016Oct03 18:41:00,977][INFO ][][fileChanged DirectoryListener.java:191][Cantidad maxima de archivos a procesar: 1]
[2016Oct03 18:41:00,980][INFO ][][fileChanged DirectoryListener.java:192][Cantidad de archivos en procesamiento: 1]
[2016Oct03 18:42:33,641][INFO ][][fileChanged DirectoryListener.java:196][No Existen Archivos por procesar...]
[2016Oct03 18:42:35,651][INFO ][][fileChanged DirectoryListener.java:133][******* En procesamiento 0]
[2016Oct03 18:42:35,653][INFO ][][fileChanged DirectoryListener.java:134][******* Cantidad Maxima Archivos 1]
[2016Oct03 18:42:35,655][INFO ][][fileChanged DirectoryListener.java:135][******* Archivos Encontrados 1]
[2016Oct03 18:42:35,657][INFO ][][fileChanged DirectoryListener.java:147][Archivo a procesar: DIG05028_1_OCCIDENTE_1.OUT]
[2016Oct03 18:42:35,666][INFO ][][getRequestFile DirectoryListener.java:265][Se validó el encabezado del archivo. Se preactivará el lote con Plan: Pre Activo BAM, Profile: 08]
[2016Oct03 18:42:35,669][INFO ][][getRequestFile DirectoryListener.java:304][Archivo DIG05028_1_OCCIDENTE_1.OUT Validado con exito]
[2016Oct03 18:42:35,671][INFO ][][getRequestFile DirectoryListener.java:308][Tiempo de ejecucion: 0s]
[2016Oct03 18:42:35,673][WARN ][][fileChanged DirectoryListener.java:176][DIG05028_1_OCCIDENTE_1.OUT]
[2016Oct03 18:42:35,986][INFO ][][configurarLogger BSSIntLogger.java:67][APLICACION: PreMasivas - VERSION: 1.0]
[2016Oct03 18:42:36,003][INFO ][][configurarLogger BSSIntLogger.java:69][DESCRIPCION: Servicios de Integracion - PreActivaciones Masivas Lineas Prepago]
[2016Oct03 18:42:36,020][INFO ][04125342996_1475536355669][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:42:36,661][INFO ][][fileChanged DirectoryListener.java:196][No Existen Archivos por procesar...]
[2016Oct03 18:42:52,125][INFO ][04125342996_1475536355669][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.mdb.ProcessInboxMDBean.onMessage(ProcessInboxMDBean.java:127)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:42:52,205][INFO ][04125342996_1475536355669][onMessage ProcessInboxRetryMDBean.java:123][Mensaje recibido con exito en la cola de REINTENTOS ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475536355669, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475536355669, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:42:35, _rc_resultado=0, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=1.0, _rc_razon=Asignacion exitosa, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:42:52,205][INFO ][04125342996_1475536355669][execute RetryQueueSubmiterDelegator.java:171][Reintentos: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola de reintentos | info: ActivationOrder enviado a la cola de reintentos | vto: {}}]
[2016Oct03 18:42:52,206][INFO ][04125342996_1475536355669][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:42:52,221][INFO ][04125342996_1475536355669][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:42:52,222][INFO ][04125342996_1475536355669][onMessage ProcessInboxMDBean.java:129][Solicitud procesada ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475536355669, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, cantLineas=1, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475536355669, _rc_razon_create=Error en la creacion del suscriptor en RTBS, pin=0000, _rc_reintentos=0.0, _rc_razon=Request enviado a la cola para el registro de estados, puk2=60525523, _rc_resultado_create=100, order=, status=0, profile=08, reintentosIL=0, puk=15045492, iccid=8958021306050000220F, pin1=1108, fecha=2016-10-03 18:42:35, relatesTo=, msisdn=04125342996, _rc_resultado=0, sMessage=, task=}}]
[2016Oct03 18:43:07,215][INFO ][04125342996_1475536355669][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.retry.mdb.ProcessInboxRetryMDBean.onMessage(ProcessInboxRetryMDBean.java:125)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:43:07,227][INFO ][04125342996_1475536355669][onMessage ProcessInboxRetryMDBean.java:123][Mensaje recibido con exito en la cola de REINTENTOS ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475536355669, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475536355669, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:42:35, _rc_resultado=0, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=2.0, _rc_razon=Asignacion exitosa, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:43:07,228][INFO ][04125342996_1475536355669][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:43:07,229][INFO ][04125342996_1475536355669][execute RetryQueueSubmiterDelegator.java:171][Reintentos: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola de reintentos | info: ActivationOrder enviado a la cola de reintentos | vto: {}}]
[2016Oct03 18:43:07,239][INFO ][04125342996_1475536355669][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:43:07,240][INFO ][04125342996_1475536355669][onMessage ProcessInboxRetryMDBean.java:127][Solicitud procesada ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:43:22,235][INFO ][04125342996_1475536355669][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.retry.mdb.ProcessInboxRetryMDBean.onMessage(ProcessInboxRetryMDBean.java:125)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.GeneratedMethodAccessor2368.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:43:22,246][INFO ][04125342996_1475536355669][onMessage ProcessInboxRetryMDBean.java:123][Mensaje recibido con exito en la cola de REINTENTOS ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475536355669, Target=crear.suscriptor.rtbs} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475536355669, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:42:35, _rc_resultado=0, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=3.0, _rc_razon=Asignacion exitosa, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
[2016Oct03 18:43:22,248][INFO ][04125342996_1475536355669][processRequest RC.java:60][Inicio de Servicio en Fase 1: crear.suscriptor.rtbs]
[2016Oct03 18:43:22,248][INFO ][04125342996_1475536355669][execute RetryQueueSubmiterDelegator.java:171][Reintentos: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola de reintentos | info: ActivationOrder enviado a la cola de reintentos | vto: {}}]
[2016Oct03 18:43:22,258][INFO ][04125342996_1475536355669][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:43:22,259][INFO ][04125342996_1475536355669][onMessage ProcessInboxRetryMDBean.java:127][Solicitud procesada ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:43:37,255][INFO ][04125342996_1475536355669][execute CreateSubscriberRTBSDelegator.java:187][Error ocurrido durante la creacion del suscriptor en RTBS]
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 15000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at ve.com.digitel.premasivas.delegator.CreateSubscriberRTBSDelegator.execute(CreateSubscriberRTBSDelegator.java:161)
	at ve.com.digitel.premasivas.rc.command.CommandChain.execute(CommandChain.java:134)
	at ve.com.digitel.premasivas.rc.RC.processRequest(RC.java:68)
	at ve.com.digitel.premasivas.retry.mdb.ProcessInboxRetryMDBean.onMessage(ProcessInboxRetryMDBean.java:125)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)
	at java.net.Socket.connect(Socket.java:461)
	at sun.reflect.GeneratedMethodAccessor2368.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	... 18 more
[2016Oct03 18:43:37,271][INFO ][04125342996_1475536355669][processRequest RC.java:60][Inicio de Servicio en Fase 1: generar.archivo.salida]
[2016Oct03 18:43:37,280][INFO ][04125342996_1475536355669][processRequest RC.java:70][Fin Servicio en Fase 1: crear.suscriptor.rtbs Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:43:37,281][INFO ][04125342996_1475536355669][onMessage ProcessInboxRetryMDBean.java:127][Solicitud procesada ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Request enviado a la cola para el registro de estados | info: ActivationOrder enviado a la cola | vto: {}}]
[2016Oct03 18:43:37,287][INFO ][04125342996_1475536355669][execute FileWriterDelegator.java:178][********************* procesados: 1]
[2016Oct03 18:43:37,289][ERROR][04125342996_1475536355669][crearArchivo FileWriterDelegator.java:301][Se instalo el lote DIG05028_1_OCCIDENTE_1.OUT con un total de lineas [1]. 
Cantidad de Errores encontrados: 1.
]
[2016Oct03 18:43:37,399][INFO ][04125342996_1475536355669][execute FileWriterDelegator.java:200][TMP eliminados de la BD. Cantidad de registros eliminados: 0]
[2016Oct03 18:43:37,401][INFO ][04125342996_1475536355669][execute FileWriterDelegator.java:229][RESP Generacion de Archivo de Salida: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Proceso completado satisfactoriamente | info:  | vto: {}}]
[2016Oct03 18:43:37,402][INFO ][04125342996_1475536355669][processRequest RC.java:70][Fin Servicio en Fase 1: generar.archivo.salida Respuesta: ve.com.digitel.bssint.ReturnValue{ | condCode: 0 | reasonCode: Archivo generado con exito | info:  | vto: {}}]
[2016Oct03 18:43:37,404][INFO ][04125342996_1475536355669][onMessage ProcessInboxMDBean.java:129][Solicitud procesada ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1475536355669, OldTarget=crear.suscriptor.rtbs, Target=generar.archivo.salida} | context: {imsi=734024020500016, plan=Pre Activo BAM, batchName=DIG05028_1_OCCIDENTE_1, traceid=04125342996_1475536355669, pin=0000, profile=08, puk=15045492, fecha=2016-10-03 18:42:35, _rc_resultado=0, cantLineas=1, _rc_razon_create=Error en la creacion del suscriptor en RTBS, _rc_reintentos=3.0, _rc_razon=Archivo generado con exito, puk2=60525523, _rc_resultado_create=100, order=, status=0, reintentosIL=0, error=09, iccid=8958021306050000220F, pin1=1108, relatesTo=, msisdn=04125342996, sMessage=, task=}}]
